### ISSUE TITLE
Linux Standard as an option

### ISSUE THREAD

**Issue by croconut** [croconut/godot-tester#11]
theres pretty major differences between standard and headless in terms of visual based testing. I'll see if the standard linux version works in a container.

**Comment by db0** [comment]
Ah, so the failed checks are definitely caused by some difference between these two? Interesting, I wonder what's causing this. I have a suspicion. Sometimes GUT is a bit finicky with regards to timing, and it could be that due to the lower overheads from headless, GUT is moving faster than Godot has time to adjust (instancing/deinstancing usually) and we end up with a false positive. I want to see if putting some extra yields before the failing tests might help.

**Comment by db0** [comment]
I am checking what is going on in Linux, and I'm just seeing some overall strange behaviour. For example in the test_DeckBuilder, on the `test_save_load_reset()` which is always failing on 4 tests, on Linux both the headless and normal godot are failing when run via cli, but windows works.

**Comment by db0** [comment]
One mystery resolved, at least in relation to the deckbuilder tests. It seems there's somehow a difference on how Linux loads the scene and how Windows does it. I don't know why, but in Linux, the order in which the cards are added to the scene is different, so in Windows I end up grabbing Test Card 3 card to test on, whereas Linux grabs Test Card 1.  

This is really unexpected but easy to solve now that I know it's happening. Very likely almost all the failing tests are failing for this reason.

Also, do you have any idea why all lines where asserts are failing are reported as -1?

**Comment by croconut** [comment]
I hope that's the only difference. I was testing locally and all tests pass on my Linux computer either way, headless or standard. But my computer is beefy so that's why my guess is leaning towards frame rate vs time issues..? Not too sure.

I have seen this kind of issue crop up in different ways in other games

**Comment by db0** [comment]
Interesting. The Linux I'm testing is a low-power VM which might be as powerful as the agent VM, so it could be that the order by which cards are instanced changes depending on the power of the VM somehow. 

I'm going to ensure the card order more and then see how many tests keep failing.

Btw, new issue, for some reason, the last two runs started timing out. Even with added extra time. I monitored one, and somehow a yield got stuck, but nothing changed in that part of the code :-/

**Comment by db0** [comment]
Yep, the card order was it.

>1120 passed 1 failed.

The last failing test seems like something similar as well so I'm sure I'll fix it.

Also, looks like the timeout didn't happen this time. Weird

**Comment by db0** [comment]
I think I understand why the difference is. Because I'm loading the card definitions in runtime from disk, somehow the slower operation of the VM changes the dictionary load order. I just need to avoid relying on the dictionary order being static.

**Comment by croconut** [comment]
You can use 1.0 which is 100% pass rate.

**Comment by croconut** [comment]
Think I'll just leave this open, don't see much benefit for this at this time

**Comment by bitwes** [comment]
Fyi, order of keys in a dictionary in Godot (and a lot of languages) is
never guaranteed to be the same.
