### ISSUE TITLE
Pass rate is considering "pending" tests as failed checks

### ISSUE THREAD

**Issue by db0** [croconut/godot-tester#12]
In your entrypoint.sh you have:

```
test_failed_string="- test"
[...]
    elif [[ $temp =~ ^$test_failed_string ]] ; then
        FAILED=$((FAILED+1))
[...]
```
But this will report a false positive on this perfectly passing report.
```
*** Run Summary ***
res://tests/integration/test_piles.gd
- test_popup_discard_view
    [Pending]:  Drawing a card from the pile, picks it from the popup
res://tests/integration/test_scripting_engine_general.gd
- test_basics
    [Pending]:  Empty does not create a ScriptingEngine object
res://tests/integration/test_scripting_engine_nested.gd
- test_draw_more_cards_than_pile_max
    [Pending]:  Test good execution of nested tasks
    [Pending]:  Test failing cost in nested cost task aborts parent script
res://tests/integration/test_scripting_engine_tasks_execute_scripts.gd
- test_no_costs_are_paid_when_target_costs_cannot_be_paid
    [Pending]:  is_cost == true execute_tasks: No costs were paid because target card could not pay costs
    [Pending]:  is_cost == false execute_tasks: Cost were paid because target card could not pay costs
    [Pending]:  is_cost == true execute_tasks: costs were paid when subject == boardseek
```

The script needs to be able to distinguish reports of pending tests from actual faulted tests.

Personally, I think this extra check on your end is not necessary. Have you seen instances where you will catch a failure by grepping for those lines starting with `- test`?

**Comment by db0** [comment]
If you want to keep this behaviour intact, another approach is to add another metric, like "assert_passrate" which will only take into account failing asserts, as reported by GUT. This way someone can specify , say 100% assert_passrate, but allow 90% passrate.

**Comment by croconut** [comment]
Never used pending as an option. 

I'll just switch to comparing passing asserts to failing asserts + script errors. I'll add a fake assert for each script failure as they remove assert visibility from the run summary.

**Comment by db0** [comment]
Sounds good, I still think a companion or mutually-exclusive metric like "max failed asserts", where you simply provide an integer, would also make sense.

**Comment by croconut** [comment]
Oh actually I remember why I set it up like that. I can look for a failing assert after getting a - test line, and as long as it's there I'll add a failed test. 

I'll also add in an assert check option so people can go by assert counts instead of tests that adds a dummy assert failure for each script error it sees.

**Comment by db0** [comment]
>Oh actually I remember why I set it up like that. I can look for a failing assert after getting a - test line, and as long as it's there I'll add a failed test.

Yes, indeed that is how it works, but unfortunately this is just a report per check ,and will include the pending tests ;)

**Comment by croconut** [comment]
I'm saying that I'll require at least one failed assert for each test marked up in the run summary as it's not making sure of that atm. 
You sound like you'd rather check asserts though so you'll want to use assert-check: true, which I'll throw in.

**Comment by db0** [comment]
>I'm saying that I'll require at least one failed assert for each test marked up in the run summary as it's not making sure of that atm.

Ah I see. That might require some creative grepping :D
