### ISSUE TITLE
Feature Request: Log level

### ISSUE THREAD

**Issue by Lyaaaaaaaaaaaaaaa** [croconut/godot-tester#16]
It could be very useful to set the level of logs in the workflow file like you can do in Godot.
![image](https://user-images.githubusercontent.com/44974422/148052431-36f77f2c-5d31-4943-8c93-f520ec277b9e.png)
When there is no error, log level at 1 is enough, but if something fails, having logs level to 2 or 3 can come handy.

**Comment by croconut** [comment]
i'll add in the ability to read in a config file which includes options for things like this. after i do that you'll want to refer to the GUT docs to set that up correctly.

**Comment by croconut** [comment]
oh this is already going to be read by default. i'll double check for compatibility with this but you should just need to create a config file as described here: https://github.com/bitwes/Gut/wiki/Command-Line#config-file

**Comment by croconut** [comment]
i'll still add in the option to specify a config file though as you might want to use different ones for prod merges

**Comment by croconut** [comment]
just as an FYI, if youre using direct-scene you'll want to set these kinds of options there as the config file is mutually exclusive with direct-scene

**Comment by Lyaaaaaaaaaaaaaaa** [comment]
Great, thank you!
