### ISSUE TITLE
Check for Script Errors in output and fail pipeline.

### ISSUE THREAD

**Issue by bitwes** [croconut/godot-tester#2]
First off it is great to see a tool I started spawning more tools!  Thanks for using GUT and making this.  

I've been thinking a lot about https://github.com/bitwes/Gut/issues/210 which has to do with errors in scripts causing a test to exit early and appear as passing.  There's been a bunch of ideas floated around but the most bulletproof approach I can think of (given Godot limitations) would be to detect Godot script errors in the output.  Can you  get to  this output in a Github Action and then fail the pipeline if you find specific strings in it?

_(BTW I found two Actions for GUT so I'm going to copy/paste this directly into the other one too.  I'm not pitting you against each other, I just don't know anything about Github Actions and I'm not comfortable picking a favorite tool-spawn (hmmm now I'm thinking about a Tool and Spawn collab).  I'm sure both pipelines are great.  When I searched the marketplace my response was "There's two?  THERE'S TWO!".   Thanks  for making `<current tool>` and  for using GUT!)_

**Comment by croconut** [comment]
I rewrote the action passing phase to parse the GUT output for total test count & passing tests count to avoid that issue.
This will be bundled into v2.1 which I will be releasing after merging PR #3.

Please keep me updated if there are changes made to your output formatting, as I'm currently reading the 
`Tests: 3`
line and the 
`5 passed 2 failed. Tests finished in 3.2s`
line to determine the action's exit code.
