### ISSUE TITLE
Parse exported XML instead of output for build pass/failure

### ISSUE THREAD

**Issue by bitwes** [croconut/godot-tester#22]
I saw #20, stating that GUT 7.3.0 broke the build.  Awhile back GUT got a [junit-xml](https://llg.cubic.org/docs/junit/) compliant export.  You'll have to do a little more work to determine if all the tests passed, since there is no summary in the XML, but parsing this output will be more reliable across GUT builds.

You can find more information about it on [the wiki](https://github.com/bitwes/Gut/wiki/Export-Test-Results)

**Comment by croconut** [comment]
Sounds like a very useful improvement for the test runner. I should be able to close these issues soon, thanks for the update

**Comment by croconut** [comment]
Looks like this is now supported, thanks to @RGonzalezTech
