### ISSUE TITLE
convert entrypoint to js

### ISSUE THREAD

**Issue by croconut** [croconut/godot-tester#28]
The entrypoint file is in bash, which is an unwieldy, barely readable language. Despite the efforts to make bash more friendly, JavaScript would make for a much more flexible/maintainable language.

That said, when using the node ecosystem, updates/maintenance essentially becomes required so I'm very open to changing to a slower moving language.

**Comment by croconut** [comment]
This should just be a 1-to-1 translation. Can do node, I think GitHub actions has a action runner setup specifically to do node. Downside is if we go outside vanilla js dependency management becomes a concern, but we can just set up dependabot and freeze it for at least a few years by using most recent LTS release.

**Comment by RGonzalezTech** [comment]
Do you plan to work on this one? I've got a couple other projects to visit this weekend, but I could also give this one a shot.

**Comment by baabcantcode** [comment]
> Do you plan to work on this one? I've got a couple other projects to visit this weekend, but I could also give this one a shot.

yeah, i dont really want to saddle you with something that im just doing because i find bash annoying lol

**Comment by RGonzalezTech** [comment]
I made time to work on this since I already had a good map of how the code works due to my recent refactoring in #27 

I just wrapped up my branch and rebased it on top of master. Those Dockerfile changes didn't play well with the `node:16` image, lol. I'll fix that Soon™
