### ISSUE TITLE
parallelize tests

### ISSUE THREAD

**Issue by croconut** [croconut/godot-tester#29]
Should swap to a job matrix and have them run in parallel.

It's just slow waiting for all the tests to complete. Should also check if Godot 4 has an stdout for when it's completed the import process, or a way to trigger that.

**Comment by RGonzalezTech** [comment]
### RE: Import Process

During testing, I was able to trigger the import process with the `--export-debug` and `--export-pack ` arguments.

Doing an export could be a reliable way to import & exit upon completion, though it will also add the overhead of the time required to export.

Let me know what you think 👍 Hope that helps.

**Comment by RGonzalezTech** [comment]
> Should also check if Godot 4 has an stdout for when it's completed the import process, or a way to trigger that.

Approved #30 , but I'm not sure if that PR resolves the import part of this issue.
