### ISSUE TITLE
Coverage exceeds 100% when using parameterization tests.

### ISSUE THREAD

**Issue by adarapata** [croconut/godot-tester#4]
I'm using a translation tool, so sorry if it's hard to understand.

Thank you for making such a great product. 👍 

When I include parameterization or perform multiple assertions in a single method, the rate becomes an inappropriate value.

Here is the current formula

`rate = Tests / Passing asserets`.

However, since passing asserets counts the number of assert methods, it may exceed the number of Tests.

I fixed it in the following way

https://github.com/adarapata/godot-tester/pull/1

However, this is not a complete solution because when a timeout occurs, it is not included in Passing asserts nor Failing asserts.

However, one problem has been solved and I am hoping that this will be taken care of once and for all. What do you think?

**Comment by croconut** [comment]
Thanks! And don't worry, it's completely readable 👍 

Your solution looks like it solves that issue, would you like to pull request? I can either add in the timeout failing to your code or in another branch, up to you. 

You'll also want to include local tests for it to run to ensure that it stays fixed.

**Comment by croconut** [comment]
I'm not exactly sure I'll be able to do much more with timeouts though. The process is being killed when it hangs / times out, so you won't be able to get test information as I'm unaware of a way to tell GUT to stop and also give me it's current information. It's more as a failsafe to prevent the action from eating up too much server time, as it's a limited resource. 

This seems like a good idea to bring up with the GUT author though!

**Comment by croconut** [comment]
Okay, I see now why I was using Tests and failing asserts instead of passing / failing asserts. I'll have to either figure out a new way to detect SCRIPT ERROR or bug the GUT author into logging more information with a verbose flag.

**Comment by adarapata** [comment]
It worked fine. Great!

Thanks for the support.
